import Sidebar from "@/components/Sidebar"
import "./globals.css"
import { Roboto } from 'next/font/google'
import Navbar from "@/components/Navbar"


export const metadata = {
  title: 'Tesk Manager',
  description: 'Generated by Next.js',
}

const roboto = Roboto({ weight: ["400", "100", "300"], subsets: ["latin"] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body  >
      <div>
        <div className="flex ">
          <Sidebar />
          <div >
            <Navbar />
            {children}
          </div>
        </div>
      </div>
        
      </body>
    </html>
  )
}
